version: '3'
services:
  postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    user: root
    #network_mode: host

  persistent-postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    user: root
    #network_mode: host
    volumes:
      - ${KGI_POSTGRES_MOUNT:-/tmp/kgi-postgres-mount}:/var/lib/postgresql/data

  processing:
    image: "kaspa-graph-inspector-processing:latest"
    depends_on:
      - persistent-postgres
    entrypoint: /bin/sh
    command: -c "/app/processing --connection-string=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable --rpcserver=${KGI_RPCSERVER} ${KGI_NETWORK_ARGS}"
    network_mode: host
    user: root
    restart: always

  api:
    image: "kaspa-graph-inspector-api:latest"
    depends_on:
      - processing
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - API_PORT=${API_PORT}
    command:
      - "npm"
      - "run"
      - "--prefix"
      - "/app"
      - "start"
    network_mode: host
    user: root
    restart: always

  web:
    image: "kaspa-graph-inspector-web:latest"
    depends_on:
      - api
    command:
      - "serve"
      - "--listen=${WEB_PORT}"
    network_mode: host
    user: root
    restart: always
